export const SAVE_USER_DATA = 'SAVE_USER_DATA';
export const CLEAR_USER_DATA = 'CLEAR_USER_DATA';
export const LOGIN_ANONYMOUS = 'LOGIN_ANONYMOUS';
export const LOGIN_USER = 'LOGIN_USER';
export const LOGOUT_USER = 'LOGOUT_USER';
export const SUBSCRIBE_PUSH_NOTIFICATION = 'SUBSCRIBE_PUSH_NOTIFICATION';
export const UNSUBSCRIBE_PUSH_NOTIFICATION = 'UNSUBSCRIBE_PUSH_NOTIFICATION';
export const SET_PUSH_NOTIFICATION_SUBSCRIPTION_STATUS = 'SET_PUSH_NOTIFICATION_SUBSCRIPTION_STATUS';


export const LOCATE_ME = 'LOCATE_ME';
export const MY_POSITION = 'MY_POSITION';