export const SAVE_USER_DATA = 'SAVE_USER_DATA';
export const CLEAR_USER_DATA = 'CLEAR_USER_DATA';
export const LOGIN_ANONYMOUS = 'LOGIN_ANONYMOUS';
export const LOGIN_USER = 'LOGIN_USER';
export const LOGOUT_USER = 'LOGOUT_USER';